@startuml
autonumber
用户->行情:访问行情30天信息
activate 行情
行情->支付中心:开通行情会员
支付中心-->行情:返回微信支付参数
行情->行情:唤醒用户微信支付
行情-->用户:微信支付页面
用户-->用户:执行微信支付
deactivate 用户
支付中心-->支付中心:微信支付回调成功
支付中心-->会员中心:支付成功，通知会员记录
支付中心-->ERP:支付成功，金蝶系统记账
deactivate 行情
@enduml