spring:
  profiles:
    active: test
  redis:
    port: 6379
    database: 0
    host: 192.168.80.130
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 5000ms
mybatis:
  typeAliasesPackage: com.xlw.demo.persist
  mapperLocations: classpath:mybatis-mappers/**/*Mapper.xml
#logging:
#  level:
#    com.sinofert.ec.service.finance.persist: debug
#    com.alibaba.nacos: warn